ovh/celery-director

setup.py

chore(setup): add classifiers and append 'celery' to the package name

---

README.md
director/commands/init.py
setup.py

- Add more info in the dotenv template.
- Add a reminder to init the database when init command is used.
- Add long description and some info to the `setup.py` for PyPi.
- Remove _License_ duplicated entry in the README.md.

Update init command, setup.py and README.md

---

director/migrations/versions/2e4550411ff1_fix_constraints.py

This PR fixes the constraint violation on postgres database.

fix(core): wrong foreign key constraint on tasks when using postgres database

---

.travis.yml
README.md

chore: execute tests in Travis

---

director/commands/workflows.py

Resolves #19
Currently:
```
$ director workflow list
+---------------+----------+--------------------------------------------------------------------------+
| Workflows (1) | Periodic | Tasks                                                                    |
+---------------+----------+--------------------------------------------------------------------------+
| ovh.ETL       |    --    | EXTRACT                                                                  |
|               |          | {'MY_GROUP': {'type': 'group', 'tasks': ['TRANSFORM_1', 'TRANSFORM_2']}} |
|               |          | LOAD                                                                     |
+---------------+----------+--------------------------------------------------------------------------+
$ director …
```

feat(cli): improve list and show workflows

---

director/__init__.py
director/api/__init__.py
director/api/workflows.py
director/commands/workflows.py
director/exceptions.py
director/extensions.py
tests/test_api.py
tests/workflows/schemas/example/simple_schema.json
tests/workflows/workflows.yml

feat(schema): handle workflow schema

---

director/api/__init__.py
director/commands/workflows.py
director/utils.py

fix(schema): hide traceback in CLI when payload is not valid

---

director/migrations/versions/05cf96d6fcae_add_task_result.py
director/models/tasks.py
director/tasks/base.py
tests/test_api.py
tests/test_builder.py
tests/test_workflows.py
tests/workflows/tasks/returns.py
tests/workflows/workflows.yml

feat(tasks): save the result in database

---

director/static/script.js

fix(ui): handle the progress status

---

director/__init__.py
director/templates/404.html
tests/test_views.py

fix(error): properly handle the 404 errors

---

director/static/script.js

Signed-off-by: Ismail Reida <ismail.reida@ovhcloud.com>

fix(ui): get workflows list on created

---

docs/docs/guides/build-workflows.md
docs/docs/guides/enable-authentication.md
docs/mkdocs.yml

Signed-off-by: Ismail Reida <ismail.reida@ovhcloud.com>

doc: add authentication and workflows queues sections

---

director/builder.py
director/extensions.py

For `workflows`, which means that all workflow's `tasks` will use the same `queue`.

Support celery queues

---

docs/mkdocs.yml

fix(doc): remove bad comma

---

.travis.yml
docs/README.md

Fix `pip install` command in `docs/README.md` and add check on Travis

fix(ci, docs): add doc building step in ci, update doc readme

---

director/settings.py
tests/test_api.py
tests/workflows/.env

fix(api): handle the default pagination setting

---

docs/mkdocs.yml

doc: add repository link in header

---

README.md
docs/docs/index.md

doc: add an example of usage in the readme

---

.travis.yml
tests/README.md
tests/test_users.py
tests/workflows/.env

chore: add postgresql tests in travis

---

director/__init__.py
director/utils.py
docs/docs/guides/build-workflows.md
tests/test_workflows.py

Support celery crontab schedules: https://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#crontab-schedules

feat: support celery crontab scheduler

---

requirements.txt

Upgrade celery and kombu versions

Fix pending workflows

---

docs/docs/api.md

doc: fix typo in POST workflow

---

.travis.yml
requirements.txt
tests/conftest.py
tests/test_api.py
tests/test_sentry.py
tests/test_workflows.py

- Fix and clean up some test cases, remove skip marker on workflow tests ;
- Fixed Werkzeug dependency to avoid bump from Flask ;
- Update Travis CI configuration to avoid issue with workflow tests.

fix tests and requirements

---

docs/docs/api.md

Add documentation for relaunch workflow api
Signed-off-by: Paulin Charliquart <paulincharliquart@gmail.com>

docs(api): add api relaunch workflow endpoint

---

docs/docs/guides/build-workflows.md

Fix cron example in the doc
Signed-off-by: Paulin Charliquart <paulincharliquart@gmail.com>

fix(doc): cron example

---

docs/docs/guides/custom-configuration.md
docs/mkdocs.yml

doc: add guide about custom configuration

---

docs/docs/guides/build-workflows.md

Signed-off-by: Paulin Charliquart <paulincharliquart@gmail.com>

docs(workflows) - specify package version for migration of schedule key

---

.github/workflows/tests.yml
README.md
docs/README.md
requirements.txt
setup.py

chore: bump flask and click dependencies

---

director/api/workflows.py
docs/docs/api.md
tests/test_api.py

Remove some parts were not working properly

fix workflow definitions

---

director/commands/init.py
director/settings.py
director/static/script.js
director/static/style.css
director/templates/index.html

Signed-off-by: Benoit Barbereau <benoit.barbereau@corp.ovh.com>

feat(ui): add definitions page and new menu

---

.github/workflows/tests.yml
director/api/workflows.py
director/builder.py
director/commands/init.py
director/commands/workflows.py
director/settings.py
director/static/script.js
director/static/style.css
director/tasks/workflows.py
director/templates/index.html
tests/test_api.py
tests/test_workflows.py
tests/workflows/tasks/time.py
tests/workflows/workflows.yml

Adding the possibility for cancelling workflow as asked in the #61 (api call) + cli + web ui

feat: Cancel workflow

---

docs/docs/guides/cleanup-workflows.md

doc: fix a formatting bug

---

docs/docs/guides/build-workflows.md

doc: add a note about the workflows name
