ovh/celery-director

README.md, director/commands/workflows.py
- The mininmal command to run a workflow is now: `director workflow run ovh.SIMPLE_ETL`
- If errors are occuring during payload parsing or not found workflows do not return zero
=> Payload optional in the director workflow run command line

tests/README.md, tests/test_workflows.py, tests/workflows/workflows.yml
- Fix the workflows YAML syntax
- Update the readme with the `director celery worker` command
- Use `is`operator when comparing with `None` ([recommanded](https://stackoverflow.com/questions/14247373/python-none-comparison-should-i-use-is-or))
=> Fix some tests, update the readme

.github/CODEOWNERS
=> chore(github): add default reviewers

director/__init__.py, director/_auto.py, director/context.py, director/settings.py
- Add: environement variable `DIRECTOR_CONFIG` (optional), export this variable if you want to specified your very own `.env`file (e.g.: `export DIRECTOR_CONFIG=/home/foobar/workflows/director.env`).
- Add: when `DIRECTOR_HOME` is not set, Director will raise a `ValueError` with a more explicit message (compared to the default message)
- Fixed: `DIRECTOR` prefixed environment variables are properly used if you do not want to use `.env `file.
=> Add new variable for the .env file

director/commands/celery.py
Fix a potential deployement issue:
`DIRECTOR_FLOWER_URL` from the `.env`file was used for the `director celery flower`command when the URL should be used only for the front.
=> fix(cli): do not use the flower url from the dotenv file

README.md, director/cli.py, director/commands/db.py, director/commands/init.py
- Give access to: `director db <flask migrate command>`
E.g.: `director db upgrade` to initialize the database.
- Move the FLOWER URL to the frontend section in the `.env` template
- Fix some typos in the README.md
=> feat(cli): add command for flask migrate

director/api/__init__.py, director/api/workflows.py, director/static/script.js, director/templates/index.html, tests/test_api.py
This PR allows a user to relaunch a workflow using API and UI (no task choice yet, the whole workflow is relaunched) :
```json
$ http POST :8000/api/workflows/309c1a62-625d-484e-ab63-027f7a31daf7/relaunch
HTTP/1.0 201 CREATED
Content-Length: 268
Content-Type: application/json
Date: Wed, 12 Feb 2020 21:47:27 GMT
Server: Werkzeug/1.0.0 Python/3.6.1
{
"created": "2020-02-12T21:47:27",
"fullname": "ovh.SIMPLE_ETL",
"id": "9264587c-3d1a-4889-aba1-f0ed2684414c",
"name": "SIMPLE_ETL",
"payload": {},
"periodic": false,
"project": "ovh",
"status": "pending",
"updated": "2020-02-12T21:47:27"
}
```
=> Relaunch workflows

director/tasks/workflows.py, tests/test_workflows.py, tests/workflows/tasks/error.py, tests/workflows/workflows.yml
The workflow state was **success** even if the last task raises a Celery error (like an `EncodeError`) because the `end` function was still called.
Note this bug was not present if an an application error (not an internal Celery exception) was raised because the full canvas stopped and the end function was not called.
**Before**
**After**
=> fix(workflows): the state was wrong when last task raises a Celery error

director/api/workflows.py, director/commands/init.py, director/settings.py, docs/docs/api.md, tests/test_api.py
The UI pagination is directly done by Vue.js using the whole response of `GET /api/workflows`.
However, after a certain period (which may vary widely), the response is too big and UI becomes unusable.
Now the API returns **1000** workflows by default, so the UI remains usable. The value can be changed with the `DIRECTOR_WORKFLOWS_PER_PAGE` configuration.
And it's still possible to fetch very old workflows using the API and the `per_page` and `page` arguments  :
```
$ curl -X GET "http://127.0.0.1:8000/api/workflows?per_page=100&page=1234"
```
=> feat(api): limit the number of workflows to return

director/models/__init__.py, director/models/users.py, director/tasks/periodic.py
fix: avoid "idle in transaction" problems on PostgreSQL following multiple queues implementation
Signed-off-by: Maxime Caruchet <maxime.caruchet@corp.ovh.com>
=> fix: avoid "idle in transaction" problems on PostgreSQL

.github/CODEOWNERS
=> chore: add Ismail and Arnaud as default reviewers

director/commands/assets.py
Update the font when using `DIRECTOR_ENABLE_CDN=false` and the `director dlassets` command.
Fix issue displaying wrong icons in Web UI.
=> fix(ui): bump mdi font version related to mdi css

director/migrations/versions/30d6f6636351_initial_migration.py
If the database engine is Postgres, Enums are saved as types in the database. So, they need to be deleted while downgrading. 
Using `.drop()` allow to drop it if it's needed (e.g. with Postgres) and do nothing if type are not saved in the database (e.g. SQLite).
This PR should solve issue #69
=> fix(migration): Add type deletion during downgrade

director/migrations/versions/30d6f6636351_initial_migration.py, director/migrations/versions/3f8466b16023_add_users_table.py, director/models/tasks.py, director/models/users.py, director/models/workflows.py, requirements.txt
`VARCHAR` lenght is require in MySQL 5.7
"VARCHAR requires a length on dialect %s" % self.dialect.name
sqlalchemy.exc.CompileError: (in table 'workflows', column 'name'): VARCHAR requires a length on dialect mysql
Put `DIRECTOR_DATABASE_URI=<proper_mysql_5.7_uri>` into `.env` file
Run `director db upgrade`
Added fixed length to `sa.String()` occurrences
=> fix: mysql string column length is required

director/__init__.py, director/tasks/base.py
This should fix errors such as "InvalidRequestError: Can't reconnect
until invalid transaction is rolled back"
Signed-off-by: Benjamin SANS <benjamin.sans@corp.ovh.com>
=> fix: make sure the session is rolled back when an unhandled exception occurred during the request.

director/__init__.py, director/commands/workflows.py, director/static/script.js, director/templates/index.html, director/utils.py, docs/docs/guides/build-workflows.md, docs/docs/guides/use-payload.md, tests/test_workflows.py
Replace PR #102
Co-authored with @PaulinCharliquart 
Do not change current behaviour when using (`workflows.yml`):
```yaml
periodic:
schedule: ...
```
Introduce keys:
```yaml
periodic:
interval: 42
```
or
```yaml
periodic:
crontab: "42 * * * *"
```
=> Refactoring periodic section in workflow declaration

director/api/workflows.py, director/models/workflows.py, director/static/script.js, docs/docs/api.md
* with_payload allows us to select if we want to return the "payload" property inside the list workflows response (defaults to True)
* do not return the payload property on list workflows call inside the UI
Signed-off-by: Maxime Caruchet <maxime.caruchet@corp.ovh.com>
=> feat: add support for with_payload arg on list workflows call

director/api/workflows.py, docs/docs/api.md, requirements.txt, tests/test_api.py
Fix issue #96. 
Add API route to get workflow definition (similar to `director workflow list`).
For each workflow with a periodic key, the next run date is added.
Signed-off-by: Paulin Charliquart <paulincharliquart@gmail.com>
=> feat(api): add workflow definition

.gitignore
- use wildcard for *.egg-info 
- ignore wildcard celery *.pid files
=> Updating .gitignore with *.egg-info/ and *.pid

requirements.txt
fix: updating flask package version and dependencies
ref issue:
https://github.com/ovh/celery-director/issues/125
ref flask 2.0.0 release:
https://flask.palletsprojects.com/en/2.0.x/changes/#version-2-0-0
- Flask upgraded from `==1.1.1` to `==2.0.0`
- Werkzeug upgraded from `==1.0.1` to `==2.0.0`
- click upgraded from `==7.0` to `==7.1.2`
Signed-off-by: George Eddie geddie@linius.com
=> Bugfix: updating flask package version and dependencies

requirements.txt
Purpose was to test installation on mac m1's which have new binaries
=> Updated requirements.txt and psycopg2-binary version

director/builder.py, tests/test_api.py, tests/test_builder.py, tests/workflows/workflows.yml
Add the possibility to route task individually in a workflow.
```yaml
example.ETL:
tasks:
- [EXTRACT, queue1]
- [TRANSFORM, queue2]
- LOAD
```
In the following case, the task-level queue overrides the workflow-level queue for the task where a queue is defined.
```yaml
example.ETL:
tasks:
- EXTRACT
- [TRANSFORM, queue2] # task-level
- LOAD
queue: queue1 # workflow-level
```
=> feat: Add per-task queue routing

director/static/script.js, director/templates/index.html
This PR removes a 500 HTTP error when refreshing (F5) the list of definitions.
=> fix: use the state to store the definitions

.github/CODEOWNERS
=> chore: update the default reviewers list

requirements.txt
This PR fixes a bug when using Celery with Python 3.7 (https://github.com/celery/celery/issues/7783).
=> chore: limit importlib-metadata package to avoid Py3.7 error

.github/CODEOWNERS
=> chore: update the list of codeowners

director/migrations/versions/2ac615d6850b_force_varchar_255.py, director/migrations/versions/46e4acde004e_add_cascade_in_task_model.py, requirements.txt
This PR switches to online mode in order to fix https://github.com/ovh/celery-director/issues/164
After merging it we'll be able to review & merge #170 and #162 (these PRs introduce new migrations).
POC:
```
$ cat director/migrations/versions/ea91724fbbb9_add_foo.py
"""add foo
Revision ID: ea91724fbbb9
Revises: 46e4acde004e
Create Date: 2022-11-22 16:38:13.759083
"""
from alembic import op
import sqlalchemy as sa
revision = 'ea91724fbbb9'
down_revision = '46e4acde004e'
branch_labels = None
depends_on = None
def upgrade():
op.add_column('workflows', sa.Column('foo', sa.String(length=255), nullable=False))
def downgrade():
op.drop_column('workflows', 'foo')
$ director db upgrade
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume …
```
=> fix: upgrade sql requirements to support the online mode

director/api/workflows.py, director/commands/workflows.py, director/migrations/versions/9d563aaa548b_add_workflow_comment.py, director/models/workflows.py, director/static/script.js, director/templates/index.html, tests/test_api.py
In order to improve the monitoring experience on the UI I added a description field to the workflows table.
This way it is possible to add specific information to each workflow instance, and distinguish between the different runs.
Of course, the description is optional. 
You can run a workflow with description in three ways :
**1. Using CLI**
```bash
director workflow run product.ORDER '{"user": 1234, "product": 1000}' --description "short description here"
```
**2. Using API**
```bash
curl --header "Content-Type: application/json" \
--request POST \
--data '{"project": "product", "name": "ORDER", \
"payload": {"user": 1234, "product": 1000}, \
"description": "short description here"}' \
http://localhost:8000/api/workflows
```
**3. Using UI, on the "Definition" page**
After running at …
=> feat: add description field to workflows

director/settings.py, requirements.txt
This PR bumps the `environs` package so it removes the warning messages in pytest:
**Before**
```
$ tests/test_api.py::test_pong -v
[...]
tests/test_api.py::test_pong
/Users/ncrocfer/Dev/deploy/celery-director/venv/lib/python3.8/site-packages/marshmallow/fields.py:949: RemovedInMarshmallow4Warning: The 'missing' argument to fields is deprecated. Use 'load_default' instead.
super().__init__(**kwargs)
-- Docs: https://docs.pytest.org/en/latest/warnings.html
======================================================================== 1 passed, 41 warnings in 0.17s ========================================================================
```
**After**
```
$ pytest tests/test_api.py::test_pong -v
tests/test_api.py . …
```
=> chore: bump the environs package

.github/workflows/tests.yml, setup.py, tests/README.md, tests/test_workflows.py
This PR adds the support for **Python 3.10 & 3.11**.
I also increment the sleep duration between the `test_cancel_workflow ` and `test_return_values ` tests to let the first one finish its work and not impact the second one (before that the 2nd test fails from time to time).
=> Add support for Python 3.10 & 3.11

requirements.txt
Related to the `  AttributeError: cython_sources` error (see https://github.com/yaml/pyyaml/issues/724).
=> bump: pyyaml
